# Generated by Django 4.2.4 on 2023-08-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ads_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегрия', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
